"""Add feature tables for CV, Job, and Video

Revision ID: e0d979095c42
Revises: 9324bef8d5b2
Create Date: 2026-01-23 09:39:14.757028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d979095c42'
down_revision = '9324bef8d5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('required_hard_skills', sa.JSON(), nullable=False),
    sa.Column('required_soft_skills', sa.JSON(), nullable=False),
    sa.Column('hard_skills_vector', sa.JSON(), nullable=False),
    sa.Column('soft_skills_vector', sa.JSON(), nullable=False),
    sa.Column('skill_count', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('cv_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('hard_skills', sa.JSON(), nullable=False),
    sa.Column('soft_skills', sa.JSON(), nullable=False),
    sa.Column('hard_skills_vector', sa.JSON(), nullable=False),
    sa.Column('soft_skills_vector', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_id')
    )
    op.create_table('video_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('cnn_features', sa.JSON(), nullable=False),
    sa.Column('soft_skill_match_score', sa.Float(), nullable=False),
    sa.Column('predicted_soft_skills', sa.JSON(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_text_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('matched_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('missing_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('matched_weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('required_weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('required_weight')
        batch_op.drop_column('matched_weight')
        batch_op.drop_column('match_ratio')

    with op.batch_alter_table('missing_skill', schema=None) as batch_op:
        batch_op.drop_column('skill_type')

    with op.batch_alter_table('matched_skill', schema=None) as batch_op:
        batch_op.drop_column('skill_type')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('posted_at')
        batch_op.drop_column('location')
        batch_op.drop_column('company')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('raw_text_path')

    op.drop_table('video_feature')
    op.drop_table('cv_feature')
    op.drop_table('job_feature')
    # ### end Alembic commands ###
